version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_POSTGRES_DRIVER: org.postgresql.Driver
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      WAIT_FOR: postgres:5432
    networks:
      - nw
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgressql/data/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
      PG_DATA: /var/lib/postgressql/data/pgdata
    restart: always
    networks:
      - nw
networks:
  nw:

#    sudo docker-compose build - сборка/пересборка 2-ух контейнеров
#    sudo docker-compose up - запуск 2-ух контейнеров
