spring:
  data:
    mongodb:
      uri: mongodb://localhost
      port: 27017
      database: awesomeMongo

mongock:
  runner-type: initializingbean
  change-logs-scan-package: ru.otus.spring.mongock.changelog

logging:
  level:
    root: ERROR





